
services:
  # --------------
  # Frontend build
  # --------------
  frontend: 
    build: ./frontend # Replace with ECR image in prod
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8000
    restart: unless-stopped
    labels:
      - "project=lumon-demo"

  # -------------
  # Backend build
  # -------------
  backend:
    build: ./backend # Replace with ECR image in prod
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/appdb
    restart: unless-stopped
    labels:
      - "project=lumon-demo"

  # --------------
  # Postgres build
  # --------------
  postgres:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${USER:-postgres}
      - POSTGRES_PASSWORD=${PASSWORD:-postgres}
      - POSTGRES_DB=${DB:-appdb}
    ports:
      - "5432:5432"
    restart: unless-stopped
    labels:
      - "project=lumon-demo"
      
volumes:
  postgres_data:
    driver: local
